// <auto-generated />
using System;
using KrillinStyles.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KrillinStyles.Migrations
{
    [DbContext(typeof(SalonContext))]
    [Migration("20190518173905_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("KrillinStyles.Database.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alt_phone_number");

                    b.Property<string>("Name");

                    b.Property<string>("Phone_number");

                    b.Property<int?>("StylistId");

                    b.HasKey("Id");

                    b.HasIndex("StylistId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("KrillinStyles.Database.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("KrillinStyles.Database.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login_name");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Session_id");

                    b.HasKey("Id");

                    b.ToTable("Stylists");
                });

            modelBuilder.Entity("KrillinStyles.Database.StylistSpecialty", b =>
                {
                    b.Property<int>("StylistId");

                    b.Property<int>("SpecialtyId");

                    b.HasKey("StylistId", "SpecialtyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("StylistSpecialties");
                });

            modelBuilder.Entity("KrillinStyles.Database.Client", b =>
                {
                    b.HasOne("KrillinStyles.Database.Stylist", "Stylist")
                        .WithMany()
                        .HasForeignKey("StylistId");
                });

            modelBuilder.Entity("KrillinStyles.Database.StylistSpecialty", b =>
                {
                    b.HasOne("KrillinStyles.Database.Specialty", "Specialty")
                        .WithMany("StylistSpecialties")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KrillinStyles.Database.Stylist", "Stylist")
                        .WithMany("StylistSpecialties")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
